baseURL = "https://mrturtle.dev"
languageCode = "en-us"
title = "MrTurtle Dev"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "MrTurtle"
    avatar = "avatar.jpg"
    # avatarDescription = "My avatar description"
    favicon = "icon.ico"
    description = """
        I don't know, text or something...
        Yeah hopefully I'll come up with something for this.
    """
    publicationYear = "2021"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "itch.io"
    # name = "Itch.io"
    pre = "<i class='fab fa-itch-io fa-lg'></i>"
    url = "https://mrturtle2005.itch.io"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/Gibatron"
    weight = 30

#[[menu.main]]
#    identifier = "discord"
#    # name = "Discord"
#    pre = "<i class='fab fa-discord fa-lg'></i>"
#    url = ""
#    weight = 40

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:mail@mrturtle.dev"
    weight = 50
